package org.adsl.client.view.gui;

import javafx.scene.SnapshotParameters;
import javafx.scene.effect.Blend;
import javafx.scene.effect.BlendMode;
import javafx.scene.effect.ColorInput;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.image.WritableImage;
import javafx.scene.paint.Color;
import javafx.scene.shape.StrokeType;
import javafx.scene.text.Text;
import javafx.scene.transform.Scale;

import java.util.HashMap;
import java.util.Map;

/**
 * Small Christmas-Chalk number used as an overlay on deck-summary icons.
 *
 * Rendering strategy — zero runtime snapshot cost:
 *   Pre-baked PNGs under /assets/badge_glyphs/ are loaded first (fast, cached).
 *   All plain-color variants are rendered WHITE and tinted at display time via
 *   Blend(MULTIPLY) — white × targetColor = targetColor exactly; transparent stays
 *   transparent.  Only falls back to a live JavaFX snapshot when no pre-baked asset
 *   exists (edge-case values outside the pre-generated ranges).
 *
 * Pre-baked directories (generated by tools/BadgeGlyphGenerator):
 *   stroke_29/  — WHITE fill + BLACK OUTSIDE stroke, 14.5pt×2
 *   plain_25/   — WHITE fill only, 12.5pt×2
 *   plain_20/   — WHITE fill only, 10pt×2
 */
public final class ChalkBadge {

    private static final double SNAPSHOT_SCALE = 2.0;

    /** Runtime-snapshot fallback cache (text:size:fill:stroke:strokeW → image). */
    private static final Map<String, Image> CACHE = new HashMap<>();

    private ChalkBadge() {}

    /**
     * Returns a chalk-font number as an {@link ImageView}.
     * Loads from a pre-baked PNG when available; falls back to a live snapshot.
     *
     * @param text    the string to render
     * @param size    font size in points (14.5, 12.5, or 10.0 have pre-baked assets)
     * @param fill    glyph fill colour
     * @param stroke  outline colour, or {@code null} for no outline
     * @param strokeW outline width (ignored when {@code stroke} is {@code null})
     */
    public static ImageView number(String text, double size, Color fill, Color stroke, double strokeW) {
        String dir = preBakedDir(size, stroke != null);
        if (dir != null) {
            String filename = sanitize(text);
            String path = "/assets/badge_glyphs/" + dir + "/" + filename + ".png";
            try {
                Image img = ImageCatalog.load(path);
                ImageView iv = new ImageView(img);
                double dispW = img.getWidth()  / SNAPSHOT_SCALE;
                double dispH = img.getHeight() / SNAPSHOT_SCALE;
                iv.setFitWidth(dispW);
                iv.setFitHeight(dispH);
                iv.setSmooth(true);
                applyTint(iv, fill, dispW, dispH);
                return iv;
            } catch (Exception ignored) {
                // fall through to runtime snapshot
            }
        }

        // Runtime snapshot fallback
        String key = text + ":" + size + ":" + fill + ":" + stroke + ":" + strokeW;
        Image img = CACHE.computeIfAbsent(key, k -> rasterize(text, size, fill, stroke, strokeW));
        ImageView v = new ImageView(img);
        v.setFitWidth(img.getWidth()  / SNAPSHOT_SCALE);
        v.setFitHeight(img.getHeight() / SNAPSHOT_SCALE);
        v.setSmooth(true);
        return v;
    }

    /**
     * Returns the pre-baked directory for the given font size and stroke flag,
     * or {@code null} if no pre-baked asset exists for this combination.
     */
    private static String preBakedDir(double size, boolean hasStroke) {
        if (hasStroke  && near(size, 14.5)) return "stroke_29";
        if (!hasStroke && near(size, 12.5)) return "plain_25";
        if (!hasStroke && near(size, 10.0)) return "plain_20";
        return null;
    }

    private static boolean near(double a, double b) { return Math.abs(a - b) < 0.05; }

    /**
     * Makes the text filename-safe.
     * Leading minus signs become "m" prefix (e.g. "-5" → "m5").
     */
    private static String sanitize(String text) {
        if (text.startsWith("-")) return "m" + text.substring(1);
        return text;
    }

    /**
     * Applies a MULTIPLY tint so that a WHITE pre-baked glyph renders in the
     * target {@code fill} colour.  White × fill = fill; transparent × fill = transparent.
     * No-op when fill is white (pre-baked colour is already correct).
     */
    private static void applyTint(ImageView iv, Color fill, double w, double h) {
        if (fill == null || isWhite(fill)) return;
        // SRC_ATOP: Result_A = node_A (transparent stays transparent),
        // Result_RGB = fill_color where glyph has pixels. MULTIPLY would make
        // the entire bounding box opaque because ColorInput has A=1 everywhere.
        iv.setEffect(new Blend(BlendMode.SRC_ATOP, null, new ColorInput(0, 0, w, h, fill)));
    }

    private static boolean isWhite(Color c) {
        return c.getRed() > 0.99 && c.getGreen() > 0.99 && c.getBlue() > 0.99;
    }

    private static Image rasterize(String text, double size, Color fill, Color stroke, double strokeW) {
        Text t = new Text(text);
        t.setFont(ImageCatalog.chalkFont(size));
        t.setFill(fill);
        if (stroke != null) {
            t.setStroke(stroke);
            t.setStrokeType(StrokeType.OUTSIDE);
            t.setStrokeWidth(strokeW);
        }
        t.applyCss();
        SnapshotParameters sp = new SnapshotParameters();
        sp.setFill(Color.TRANSPARENT);
        sp.setTransform(new Scale(SNAPSHOT_SCALE, SNAPSHOT_SCALE));
        return t.snapshot(sp, null);
    }
}
